# Generated by Django 4.1.3 on 2022-11-12 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=200)),
                ("nickname", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "level",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                ("classe", models.TextField(max_length=200)),
                ("xp", models.IntegerField()),
                ("title", models.TextField(blank=True, max_length=200, null=True)),
                ("occupation", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "ac",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "hp",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "current_hp",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "speed",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "init",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "strength",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "agility",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "stamina",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "personality",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "intelligence",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "luck",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "reflex",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "fortitude",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "will",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                ("alignment", models.TextField(max_length=200)),
                ("birthsign", models.TextField(max_length=200)),
                ("birthsign_effect", models.TextField(max_length=200)),
                ("languages", models.TextField(blank=True, max_length=200, null=True)),
                ("patron", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "spells_known",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                ("inventory", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "proficient_weapons",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                (
                    "lucky_weapon",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                (
                    "lucky_spell",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                ("dead", models.BooleanField()),
                ("curses", models.TextField(blank=True, max_length=200, null=True)),
                ("deity", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
