# Generated by Django 4.1.3 on 2022-11-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0002_alter_character_init"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="ac",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="agility",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="current_hp",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="fortitude",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="hp",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="intelligence",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="level",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="luck",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="personality",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="reflex",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="speed",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="stamina",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="strength",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="will",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
